LANGUAGE_TAGS = [
    "chinese",
    "japanese",
    "korean",
    "english",
    "french",
    "spanish",
    "thai",
    "italian",
    "german",
    "russian",
    "vietnamese"
]

ECOSYSTEM_TAGS =  [
    "ethereum",
    "solana",
    "sui",
    "aptos",
    "near",
    "polkadot",
    "avalanche",
    "bnb_chain",
    "cardano",
    "tezos",
    "arbitrum",
    "optimism",
    "zkSync",
    "starknet",
    "polygon_pos",
    "polygon_zkevm",
    "base",
    "mantle",
    "linea",
    "scroll",
    "cosmos",
    "hyperliquid",
    "virtuals",
    "injective",
    "rollups",
    "zk_rollups",
]


USER_TYPE_TAGS = [
    "developer",
    "founder & CEO",
    "nft_collector",
    "alpha_hunter",
    "gamefi_player",
    "defi_user",
    "airdrop_hunter",
    "meme_creator",
    "technical_sharer",
    "trader",
    "market_maker",
    "arbitrageur",
    "yield_farmer",
    "onchain_analyst",
    "community",
    "researcher",
    "other"
]